spring:
  application:
    name: ABC
  datasource:
    username: root
    password: lzr20040113
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888

app:
  upload:
    base-dir: /User/lilns/demo/image
    product-image-dir: ${app.upload.base-dir}/product-images